sites:
  https://raviqqe.com/:
    recurse: true
    check:
      content: true
  https://raviqqe.com/stak:
    recurse: 42
  https://raviqqe.com/muffet:
  https://raviqqe.com/muffy:
default:
  headers:
    user-agent: Muffy/1.0
  status:
    - 200
    - 403
  scheme:
    accept:
      - http
      - https
  max_redirects: 8
  max_age: 7d
exclude:
  - https://www.gnu.org/guile
