sites:
  https://raviqqe.com/:
    recurse: true
    check:
      - link
      - html_element
  https://raviqqe.com/stak:
    recurse: true
  https://raviqqe.com/muffet:
    recurse: true
  https://raviqqe.com/muffy:
    recurse: true
  https://www.gnu.org/guile:
    exclude: true
default:
  headers:
    user-agent: Muffy/1.0
  status:
    - 200
    - 403
  scheme:
    accept:
      - http
      - https
  max_redirects: 8
  max_age: 7d
cache: true
