[templates.default]
max_redirects = 8
schemes = ["https"]
statuses = [200]
timeout = "30s"
cache.max_age = "1h"

[templates.default.headers]
user-agent = "Muffy/0.2.0"

[templates.main]
extend = "default"
recurse = true

[templates.external]
extend = "default"
statuses = [200, 403, 429]

[sites."https://raviqqe.com/"]
extend = "main"

[sites."https://raviqqe.com/muffet"]
extend = "main"

[sites."https://raviqqe.com/muffy"]
extend = "main"

[sites."https://raviqqe.com/stak"]
extend = "main"

[sites."https://crates.io/"]
extend = "external"

[sites."https://aclanthology.org/"]
exclude = true

[sites."https://www.gnu.org/software/guile/"]
exclude = true

[sites."*"]
extend = "external"
