[sites."https://raviqqe.com/"]
recurse = true

[sites."https://raviqqe.com/muffet"]
recurse = true

[sites."https://raviqqe.com/muffy"]
recurse = true

[sites."https://raviqqe.com/stak"]
recurse = true

[sites."https://crates.io/"]
extend = "external"

[sites."https://aclanthology.org/"]
exclude = true

[sites."https://www.gnu.org/software/guile/"]
exclude = true

[configs.default]
max_redirects = 8
schemes = ["http", "https"]
statuses = [200]
timeout = "30s"
cache.max_age = "1h"

[configs.default.headers]
user-agent = "Muffy/0.2.0"

[configs.external]
extend = "default"
statuses = [200, 403, 429]
