[sites.default]
max_redirects = 8
schemes = ["https"]
statuses = [200]
timeout = "30s"
cache.max_age = "5m"

[sites.default.headers]
user-agent = "Muffy/0.2.0"

[sites.main]
extend = "default"
roots = [
  "https://raviqqe.com/",
  "https://raviqqe.com/muffet",
  "https://raviqqe.com/muffy",
  "https://raviqqe.com/stak"
]
recurse = true

[sites."https://crates.io/"]
extend = "default"
statuses = [200, 403, 429]
cache.max_age = "1h"

[sites.excluded]
roots = ["https://aclanthology.org/", "https://www.gnu.org/software/guile/"]
exclude = true
